import React, { useEffect, useState } from 'react';
import ReactGA from 'react-ga4';
import {
  Container, Typography, Paper, Accordion, AccordionSummary, AccordionDetails,
 Snackbar, Alert, useTheme, useMediaQuery
} from '@mui/material';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import { styled } from '@mui/system';

// Initialize Google Analytics for page tracking
ReactGA.initialize('G-823N1D2MNZ');

// Custom styled components
const StyledContainer = styled(Container)(({ theme }) => ({
  padding: theme.spacing(4),
  maxWidth: '800px',
  backgroundColor: theme.palette.background.default,
  [theme.breakpoints.down('sm')]: {
    padding: theme.spacing(2),
    maxWidth: '100%',
  },
}));

const StyledPaper = styled(Paper)(({ theme }) => ({
  padding: theme.spacing(4),
  backgroundColor: '#f5f5f5',
  [theme.breakpoints.down('sm')]: {
    padding: theme.spacing(2),
  },
}));

const Title = styled(Typography)(({ theme }) => ({
  fontWeight: 700,
  marginBottom: theme.spacing(2),
  fontSize: '2rem', // Smaller font
  textAlign: 'center',
  fontFamily: '"Roboto", sans-serif',
  [theme.breakpoints.down('sm')]: {
    fontSize: '1.5rem',
  },
}));

const SectionHeading = styled(Typography)(({ theme }) => ({
  fontWeight: 600,
  marginTop: theme.spacing(3),
  marginBottom: theme.spacing(1),
  fontSize: '1.25rem',
  display: 'flex',
  alignItems: 'center',
  fontFamily: '"Roboto", sans-serif',
  [theme.breakpoints.down('sm')]: {
    fontSize: '1rem',
  },
}));

const FAQPage = () => {
  const theme = useTheme();
  const isSmallScreen = useMediaQuery(theme.breakpoints.down('sm'));
  const [expanded, setExpanded] = useState(false);

  useEffect(() => {
    // Track page view for Google Analytics
    ReactGA.send({ hitType: 'pageview', page: '/faq' });
  }, []);

  const handleChange = (panel) => (event, isExpanded) => {
    setExpanded(isExpanded ? panel : false);
  };

  return (
    <StyledContainer maxWidth="lg">
      <StyledPaper elevation={3}>
        <Title variant="h2" gutterBottom>
          Frequently Asked Questions (FAQ)
        </Title>

        <Typography variant="body1" paragraph>
          Welcome to our FAQ page! Below you’ll find answers to some of the most common questions about our services and policies.
        </Typography>

        {/* Accordion with FAQ items */}
        <Accordion expanded={expanded === 'panel1'} onChange={handleChange('panel1')}>
          <AccordionSummary expandIcon={<ExpandMoreIcon />} aria-controls="panel1-content" id="panel1-header">
            <Typography variant="subtitle1">1. What is DogSwap?</Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography variant="body2">
            DogSwap is a decentralized finance (DeFi) platform where users can swap tokens, provide liquidity, and earn rewards. It operates on the MintMe Network and uses the $BONE token for various functions, including staking and governance.
            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion expanded={expanded === 'panel2'} onChange={handleChange('panel2')}>
          <AccordionSummary expandIcon={<ExpandMoreIcon />} aria-controls="panel2-content" id="panel2-header">
            <Typography variant="subtitle1">2. How do I swap tokens on DogSwap?</Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography variant="body2">
            To swap tokens on DogSwap, go to the "Swap" section on the platform, select the tokens you want to trade, enter the amount, and confirm the swap. Your new tokens will appear in your wallet once the transaction is completed.            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion expanded={expanded === 'panel3'} onChange={handleChange('panel3')}>
          <AccordionSummary expandIcon={<ExpandMoreIcon />} aria-controls="panel3-content" id="panel3-header">
            <Typography variant="subtitle1">3. What are liquidity pools and how do they work?</Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography variant="body2">
            Liquidity pools are collections of tokens provided by users to facilitate trading on the platform. Users deposit tokens into these pools and earn rewards based on the trading fees generated by the pool.            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion expanded={expanded === 'panel4'} onChange={handleChange('panel4')}>
          <AccordionSummary expandIcon={<ExpandMoreIcon />} aria-controls="panel4-content" id="panel4-header">
            <Typography variant="subtitle1">4. How can I provide liquidity on DogSwap?</Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography variant="body2">
            To provide liquidity, go to the "Liquidity" section, choose the tokens you want to add to a pool, and specify the amount. Once you add your tokens, you'll receive LP tokens representing your share in the pool.            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion expanded={expanded === 'panel5'} onChange={handleChange('panel5')}>
          <AccordionSummary expandIcon={<ExpandMoreIcon />} aria-controls="panel5-content" id="panel5-header">
            <Typography variant="subtitle1">5. What is $BONE and how is it used?</Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography variant="body2">
            $BONE is the native token of DogSwap. It is used for staking, earning rewards, participating in governance, and incentivizing liquidity provision on the platform.            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion expanded={expanded === 'panel6'} onChange={handleChange('panel6')}>
          <AccordionSummary expandIcon={<ExpandMoreIcon />} aria-controls="panel6-content" id="panel6-header">
            <Typography variant="subtitle1">6. How can I stake $BONE tokens?</Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography variant="body2">
            To stake $BONE tokens, navigate to the "Staking" section on DogSwap, choose the staking pool, enter the amount of $BONE you want to stake, and confirm your action. Staking earns you rewards and gives you voting power.            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion expanded={expanded === 'panel7'} onChange={handleChange('panel7')}>
          <AccordionSummary expandIcon={<ExpandMoreIcon />} aria-controls="panel7-content" id="panel7-header">
            <Typography variant="subtitle1">7. What are the benefits of staking $BONE tokens?</Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography variant="body2">
            Staking $BONE tokens allows you to earn rewards, participate in governance decisions, and support the DogSwap ecosystem. Stakers receive additional $BONE tokens as rewards.            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion expanded={expanded === 'panel8'} onChange={handleChange('panel8')}>
          <AccordionSummary expandIcon={<ExpandMoreIcon />} aria-controls="panel8-content" id="panel8-header">
            <Typography variant="subtitle1">8. How does DogSwap ensure the security of my funds?</Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography variant="body2">
            DogSwap uses smart contracts to manage trades and liquidity pools, which are audited to ensure security. Additionally, the platform follows best practices in DeFi security to protect user funds.            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion expanded={expanded === 'panel9'} onChange={handleChange('panel9')}>
          <AccordionSummary expandIcon={<ExpandMoreIcon />} aria-controls="panel9-content" id="panel9-header">
            <Typography variant="subtitle1">9. What is the governance system on DogSwap?</Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography variant="body2">
            The governance system allows $BONE token holders to vote on proposals and decisions affecting the platform’s development and operations. This system ensures that the community has a say in the future of DogSwap.            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion expanded={expanded === 'panel10'} onChange={handleChange('panel10')}>
          <AccordionSummary expandIcon={<ExpandMoreIcon />} aria-controls="panel10-content" id="panel10-header">
            <Typography variant="subtitle1">10. How can I get support if I encounter issues on DogSwap?</Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography variant="body2">
            If you encounter any issues, you can reach out to our support team via the chatbot on the website, join our Discord community for real-time assistance, or check our documentation and FAQs for solutions.            </Typography>
          </AccordionDetails>
        </Accordion>

        {/* Snackbar for notifications */}
        <Snackbar open={false} autoHideDuration={6000}>
          <Alert severity="info">Thank you for checking our FAQ!</Alert>
        </Snackbar>
      </StyledPaper>
    </StyledContainer>
  );
};

export default FAQPage;
